osx_image: xcode61
language: objective-c
before_install: gem install cocoapods xcpretty -N
cache: cocoapods
podfile: Example/Podfile
script:
    - export LC_CTYPE=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - set -o pipefail && xcodebuild -workspace Example/SSDynamicTextExample.xcworkspace -scheme SSDynamicTextExample -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" clean test ONLY_ACTIVE_ARCH=NO | xcpretty -c
